# https://docs.conda.io/projects/conda-build/en/latest/resources/define-metadata.html
{% set version = "0.0.1" %}
{% set build = "0" %}

package:
  name: armadillo
  version: {{ version }}

about:
  home: https://armadillo.dhvi.duke.edu/info
  summary: Calculate the probability of amino acid mutations of antibody sequences

source:
  git_url: https://github.com/ShawHahnLab/ARMADiLLO.git
  git_branch: conda
  git_depth: 1

build:
  number: {{ build }}

requirements:
  build:
    - gxx
    - boost
    - libboost-devel
  run:
    - boost
    - libstdcxx-ng
    - libgcc-ng
